services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - dbvolume:/var/lib/postgresql/data
      - ./.postgres/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql

  temporal-ui:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.22.3
    ports:
      - 8080:8080

  temporal:
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=postgresql
    image: temporalio/auto-setup:1.22.4
    ports:
      - 7233:7233

volumes:
  dbvolume:
