# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: pr
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.200-preview.23624.5

      - name: Display dotnet version
        run: dotnet --version

      - name: restore
        run: dotnet restore

      - name: format check
        run: dotnet format --verify-no-changes

      - name: build
        run: dotnet build --Configuration Release
